parameters:
    synth_memcached.manager: Synth\MemcacheBundle\Model\MemcacheManager

services:
    synth_memcached:
        class: %synth_memcached.manager%
        arguments: [%synth_memcached.memcached_class%, %synth_memcached.servers%, %synth_memcached.key_prefix%]
