parameters:
    synth_memcache.manager: Synth\MemcacheBundle\Model\MemcacheManager

services:
    synth_memcache:
        class: %synth_memcache.manager%
        arguments: [%synth_memcache.memcache_class%, %synth_memcache.servers%, %synth_memcache.key_prefix%]
